// 治療家クエスト ─ 全100クエストデータ
const WORLDS = [
  {
    id: 1,
    name: "開業の洞窟",
    subtitle: "開業キット",
    icon: "⛏️",
    color: "#e67e22",
    bgGradient: "linear-gradient(135deg, #e67e22 0%, #d35400 100%)",
    description: "冒険に出る前に、装備を全部揃える。何も持たずに冒険に出たら死ぬ。",
    harryIntro: "まずは装備を揃えよう！ 何も持たずに冒険に出たら、最初のスライムにもやられちゃうよ！",
    harryComplete: "装備が全部揃ったね！ これで冒険に出る準備は完璧だ！ 次は心の修行だよ！",
    reward: "開業に必要な約20個のツールが全て揃った状態",
    title: "装備完了の冒険者",
    levelRange: [1, 5],
    folder: "digital-product-8-kaigyou",
    quests: [
      { id: 1, name: "冒険者登録", enemy: "何から手をつけていいかわからない", clear: "開業届・保健所届出を提出した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 2, name: "青の書", enemy: "青色申告って何？", clear: "青色申告承認申請書を税務署に提出した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 3, name: "問診の巻物", enemy: "問診票がない・何を聞けばいいかわからない", clear: "問診票テンプレートを自分の院用にカスタマイズして印刷した", isBoss: false, chapter: "02_chapter2.md" },
      { id: 4, name: "カルテの石版", enemy: "施術記録のフォーマットがない", clear: "カルテ・検査票テンプレートを作成した", isBoss: false, chapter: "02_chapter2.md" },
      { id: 5, name: "戦士の証", enemy: "診察券も回数券もない", clear: "診察券・回数券・紹介カードを作成した", isBoss: false, chapter: "03_chapter3.md" },
      { id: 6, name: "旅の名刺", enemy: "自分を紹介するものがない", clear: "名刺100枚＋リーフレットを作成・常に20枚携帯する体制を整えた", isBoss: false, chapter: "04_chapter4.md" },
      { id: 7, name: "拠点の整備", enemy: "院内に何を置けばいいかわからない", clear: "初診資料・料金表・患者様の声カード・口コミ依頼カードを作成した", isBoss: false, chapter: "05_chapter5.md" },
      { id: 8, name: "デジタルの鎧", enemy: "ホームページがない", clear: "WordPressまたは無料サービスでHPの最小構成を公開した", isBoss: false, chapter: "06_chapter6.md" },
      { id: 9, name: "地図に載る", enemy: "ネット上に院の情報がない", clear: "Googleビジネスプロフィールに登録し、写真・営業時間・詳細情報を入力した", isBoss: false, chapter: "06_chapter6.md" },
      { id: 10, name: "声の拡声器", enemy: "SNSアカウントがない", clear: "SNSアカウント（Instagram/X/Facebook）を1つ開設し、最初の投稿をした", isBoss: false, chapter: "06_chapter6.md" },
      { id: 11, name: "旗を立てる", enemy: "通りがかりの人に気づかれない", clear: "院の前にのぼり・看板を設置した", isBoss: false, chapter: "06_chapter6.md" },
      { id: 12, name: "近隣への挨拶", enemy: "周りのお店と面識がない", clear: "近隣のお店5軒に挨拶に行き、名刺またはリーフレットを渡した", isBoss: false, chapter: "06_chapter6.md" },
      { id: 13, name: "補助金ドラゴン", enemy: "開業資金が足りない", clear: "小規模事業者持続化補助金 or IT導入補助金の申請書を作成した", isBoss: true, chapter: "07_bonus.md" }
    ]
  },
  {
    id: 2,
    name: "心の神殿",
    subtitle: "マインドセット",
    icon: "🧘",
    color: "#9b59b6",
    bgGradient: "linear-gradient(135deg, #9b59b6 0%, #8e44ad 100%)",
    description: "装備は揃った。でも心が整っていないと、最初の敵にやられる。",
    harryIntro: "装備だけじゃダメなんだ。心の中にある『見えない敵』を倒さないと、冒険は始まらないよ。",
    harryComplete: "心の呪いを全部解いたね！ もう「また来てください」が自然に言えるはず。さあ、街に出よう！",
    reward: "「また来てください」が自然に言えるマインド",
    title: "呪いを解いた者",
    levelRange: [6, 13],
    folder: "digital-product-1",
    quests: [
      { id: 14, name: "お金の呪い", enemy: "お金をもらうことへの罪悪感", clear: "お金のブロックを5項目チェックし、自分のスコアを把握した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 15, name: "呪いの正体", enemy: "なぜ罪悪感があるのかわからない", clear: "3点以上の項目に「なぜ？」を3〜5回繰り返し、根っこを言語化した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 16, name: "視点の転換", enemy: "言えない言葉がある", clear: "「患者さんに伝えることで、患者さんにどんな良いことがあるか」を書き直した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 17, name: "最初の一歩", enemy: "提案する勇気が出ない", clear: "今週来た患者さん全員に、帰り際に一言だけ次回の提案をした", isBoss: false, chapter: "02_chapter2.md" },
      { id: 18, name: "恐怖の幻影", enemy: "断られるのが怖い", clear: "「断られた時に実際に何が起きたか」を書き出し、恐怖の実体を確認した", isBoss: false, chapter: "02_chapter2.md" },
      { id: 19, name: "沈黙のコスト", enemy: "提案しないことの損失に気づいていない", clear: "先月「提案しなかった患者さん」の人数と、失った売上を計算した", isBoss: false, chapter: "02_chapter2.md" },
      { id: 20, name: "断りの盾", enemy: "断られた後の対応がわからない", clear: "断られた後に使う「マイフレーズ」を1つ作成した", isBoss: false, chapter: "02_chapter2.md" },
      { id: 21, name: "天井の鎖", enemy: "「田舎だから無理」「一人だから限界がある」", clear: "自分の「言い訳の天井」を書き出し、内と外に分類した", isBoss: false, chapter: "03_chapter3.md" },
      { id: 22, name: "先人の足跡", enemy: "同じ環境で成功してる人なんていない", clear: "似た環境でうまくいっている事例を3つ見つけて分析した", isBoss: false, chapter: "03_chapter3.md" },
      { id: 23, name: "守りの誇り", enemy: "「お勤めに出るのは独立の失敗」", clear: "「守りの収入」という戦略を理解し、お勤め先を1つ調べた", isBoss: false, chapter: "03_chapter3.md" },
      { id: 24, name: "確信の種", enemy: "自分の技術に自信がない", clear: "患者さんの変化記録を開始し、得意領域のトップ3を特定した", isBoss: false, chapter: "04_chapter4.md" },
      { id: 25, name: "30日の実験", enemy: "提案しても意味がない気がする", clear: "30日間すべての患者さんに来院頻度を提案し、結果を記録した", isBoss: false, chapter: "04_chapter4.md" },
      { id: 26, name: "対立の魔王", enemy: "売上と貢献は矛盾する", clear: "「貢献の連鎖」を3人分書き出し、売上＝貢献の結果と理解した", isBoss: true, chapter: "05_chapter5.md" }
    ]
  },
  {
    id: 3,
    name: "出会いの街",
    subtitle: "集客",
    icon: "🏘️",
    color: "#27ae60",
    bgGradient: "linear-gradient(135deg, #27ae60 0%, #219a52 100%)",
    description: "心の準備ができた。いよいよ街に出て、人と出会い、患者さんを集める。",
    harryIntro: "心の準備はOK！ いよいよ街に出るよ。最初は誰も君のことを知らない。でも大丈夫、一人ずつ出会っていこう！",
    harryComplete: "すごい！ 患者さんが安定して来てくれるようになったね！ 次は技を磨く番だ！",
    reward: "患者さんが安定して来院する仕組み",
    title: "街の顔",
    levelRange: [14, 20],
    folder: "digital-product-2",
    quests: [
      { id: 27, name: "最初の仲間", enemy: "知り合いがゼロ", clear: "地域のキーパーソン（民生委員・商工会・地域団体など）を1人見つけて会った", isBoss: false, chapter: "01_chapter1.md" },
      { id: 28, name: "組織に飛び込む", enemy: "人脈の広げ方がわからない", clear: "地域の組織・コミュニティに1つ参加し、毎週顔を出す習慣を作った", isBoss: false, chapter: "02_chapter2.md" },
      { id: 29, name: "家族の力", enemy: "院だけでは地域に溶け込めない", clear: "家族で参加できる地域活動を1つ見つけて継続参加を始めた", isBoss: false, chapter: "02_chapter2.md" },
      { id: 30, name: "4つの武器", enemy: "集客ツールが足りない", clear: "HP・看板・チラシ・Googleビジネスの4つを全て整備した", isBoss: false, chapter: "03_chapter3.md" },
      { id: 31, name: "口コミの循環", enemy: "口コミが入らない", clear: "Googleビジネスで口コミを1件もらい、返信した", isBoss: false, chapter: "03_chapter3.md" },
      { id: 32, name: "発信の習慣", enemy: "SNSが続かない", clear: "院の日常・セルフケア情報を週3回以上、2週間継続投稿した", isBoss: false, chapter: "03_chapter3.md" },
      { id: 33, name: "守りの砦", enemy: "収入が不安定で焦る", clear: "お勤め先を1つ確保した（デイサービス・訪問マッサージなど）", isBoss: false, chapter: "04_chapter4.md" },
      { id: 34, name: "売上の公式", enemy: "売上の上げ方がわからない", clear: "自分の月商を「客数 × 単価 × 来院頻度」に分解し、ボトルネックを特定した", isBoss: false, chapter: "04_chapter4.md" },
      { id: 35, name: "3つの一言", enemy: "施術後の対応が曖昧", clear: "施術後に必ず3つ伝える習慣を作った（変化の言語化・セルフケア・次回日程）", isBoss: false, chapter: "04_chapter4.md" },
      { id: 36, name: "価格の剣", enemy: "メニューと料金が決められない", clear: "メニューを3つ以内に絞り、時間ではなく価値で価格を設定した", isBoss: false, chapter: "04_chapter4.md" },
      { id: 37, name: "回数券の盾", enemy: "リピートの仕組みがない", clear: "回数券を設計した（5〜15%割引・有効期限あり・2〜3回目以降に提案）", isBoss: false, chapter: "04_chapter4.md" },
      { id: 38, name: "値上げの階段", enemy: "安すぎるけど上げる勇気がない", clear: "予約が8割以上埋まった月を確認し、500〜1,000円の値上げを実施した", isBoss: false, chapter: "04_chapter4.md" },
      { id: 39, name: "時間の盾", enemy: "忙しすぎて倒れそう", clear: "理想の1日・1週間スケジュールを作り、先に週休2日を設定した", isBoss: false, chapter: "05_chapter5.md" },
      { id: 40, name: "仕組みの番人", enemy: "自分がいないと回らない", clear: "予約システム（LINE/Web）を導入し、24時間予約が入る仕組みを作った", isBoss: true, chapter: "05_chapter5.md" }
    ]
  },
  {
    id: 4,
    name: "技の塔",
    subtitle: "施術の仕組み化",
    icon: "🗼",
    color: "#e74c3c",
    bgGradient: "linear-gradient(135deg, #e74c3c 0%, #c0392b 100%)",
    description: "患者さんが来るようになった。今度は「通い続けてもらう」技を磨く。",
    harryIntro: "患者さんが来てくれるようになったね！ でも『また来てもらう』にはコツがあるんだ。技の塔で修行しよう！",
    harryComplete: "技の修行が完了した！ リピート率80%超え、すごいよ！ 次は自分だけのブランドを作ろう！",
    reward: "リピート率80%超の施術フロー",
    title: "技の継承者",
    levelRange: [21, 30],
    folder: "digital-product-3",
    quests: [
      { id: 41, name: "問診の地図", enemy: "患者さんの全体像が掴めない", clear: "初回問診で5つの質問（主訴・生活・治療歴・ゴール・通院制約）を全て聞く習慣を作った", isBoss: false, chapter: "01_chapter1.md" },
      { id: 42, name: "聞き返しの術", enemy: "聞いた情報がバラバラ", clear: "問診の最後に、聞いた内容をまとめて患者さんに伝え返すプロセスを追加した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 43, name: "検査の目", enemy: "体の状態を客観的に測れない", clear: "検査項目を3〜5個に絞り、初回の検査結果を必ず記録する習慣を作った", isBoss: false, chapter: "02_chapter2.md" },
      { id: 44, name: "定期検査の暦", enemy: "いつ再検査すればいいかわからない", clear: "定期検査のタイミング（ペース変更時）と項目を決め、検査記録シートを運用開始した", isBoss: false, chapter: "02_chapter2.md" },
      { id: 45, name: "4ステージの眼", enemy: "良くなっているか判断できない", clear: "今の患者さん3人のステージ（急性期→回復期→安定期→メンテナンス期）を判定した", isBoss: false, chapter: "03_chapter3.md" },
      { id: 46, name: "機能の軸", enemy: "痛みの有無だけで判断している", clear: "評価を「症状ベース」から「機能ベース」（体が何をどこまでできるか）に切り替えた", isBoss: false, chapter: "03_chapter3.md" },
      { id: 47, name: "ステージ2の壁", enemy: "日常生活に支障がなくなると来なくなる", clear: "ステージ2の患者さんに「ステージ3へ向かう必要性」を伝える言葉を用意した", isBoss: false, chapter: "03_chapter3.md" },
      { id: 48, name: "生活の処方箋", enemy: "施術だけでは限界がある", clear: "施術後に「一つだけ」のポジティブな生活指導を伝える習慣を開始した", isBoss: false, chapter: "04_chapter4.md" },
      { id: 49, name: "禁止令の言い換え", enemy: "「〜しないでください」ばかり言ってしまう", clear: "全ての禁止指導をポジティブな行動提案に言い換えた", isBoss: false, chapter: "04_chapter4.md" },
      { id: 50, name: "安心の声", enemy: "患者さんが不安そうに帰る", clear: "施術後に「良くなってますよ。いい方向に進んでいます」と毎回伝える習慣を作った", isBoss: false, chapter: "04_chapter4.md" },
      { id: 51, name: "指令モード", enemy: "「また痛くなったら来てください」と言ってしまう", clear: "初回施術後に来院頻度を「提案」ではなく「伝える」モードで話した", isBoss: false, chapter: "05_chapter5.md" },
      { id: 52, name: "ペースの管理", enemy: "来院頻度の変更タイミングがわからない", clear: "来院ペース管理シートを作成し、フェーズ・頻度・移行根拠を記録し始めた", isBoss: false, chapter: "05_chapter5.md" },
      { id: 53, name: "来院頻度の竜王", enemy: "「週2回→週1回→2週に1回→月1回」ができない", clear: "3人以上の患者さんで段階的ペース管理を実行した", isBoss: true, chapter: "05_chapter5.md" }
    ]
  },
  {
    id: 5,
    name: "旗の丘",
    subtitle: "ブランディング",
    icon: "🚩",
    color: "#f39c12",
    bgGradient: "linear-gradient(135deg, #f39c12 0%, #e67e22 100%)",
    description: "技を磨いた。次は「自分の旗」を立てる。誰にも真似できないブランドを作る。",
    harryIntro: "技が磨かれたね！ でもまだ『あの先生』って呼ばれてないでしょ？ 自分だけの旗を立てよう！",
    harryComplete: "ブランドが完成した！ もう「あの先生のところ」って覚えてもらえるね！ 次は仕組みを作ろう！",
    reward: "「あの先生のところ」と覚えてもらえるブランド",
    title: "旗を立てた者",
    levelRange: [31, 40],
    folder: "digital-product-5",
    quests: [
      { id: 54, name: "自分の名", enemy: "何が強みかわからない", clear: "「○○の施術家が、○○の方に、○○を提供する」を一言にまとめた", isBoss: false, chapter: "01_chapter1.md" },
      { id: 55, name: "ありがとうの分析", enemy: "強みが見つからない", clear: "患者さんに一番よく言われる「ありがとう」を3つ書き出し、共通点を分析した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 56, name: "看板の専門性", enemy: "何でも屋になっている", clear: "看板に出す専門性を1つ決めた（来た患者さんには全対応する前提で）", isBoss: false, chapter: "01_chapter1.md" },
      { id: 57, name: "本の種", enemy: "発信が続かない", clear: "「毎日の発信 ＝ 本の素材」と理解し、テーマを決めて1週間毎日発信した", isBoss: false, chapter: "02_chapter2.md" },
      { id: 58, name: "出版の道", enemy: "本なんて自分には書けない", clear: "KDPアカウントを開設し、出版ロードマップ（6ステップ）を作成した", isBoss: false, chapter: "02_chapter2.md" },
      { id: 59, name: "キャラの誕生", enemy: "記憶に残らない院", clear: "マスコットキャラクターのモチーフ・性格・名前を決め、基本ポーズを作成した", isBoss: false, chapter: "03_chapter3.md" },
      { id: 60, name: "キャラの冒険", enemy: "キャラクターが活用されていない", clear: "キャラクターを院内（看板・待合室・料金表）と紙ツール（診察券・名刺）に配置した", isBoss: false, chapter: "03_chapter3.md" },
      { id: 61, name: "デジタルの顔", enemy: "ネット上でキャラが使われていない", clear: "SNSアイコン・HP・LINE公式・ブログアイキャッチにキャラクターを統一配置した", isBoss: false, chapter: "03_chapter3.md" },
      { id: 62, name: "色を決める", enemy: "印象がバラバラ", clear: "ブランドカラー（メイン1色＋サブ1〜2色）を決定した", isBoss: false, chapter: "04_chapter4.md" },
      { id: 63, name: "言葉を揃える", enemy: "キャッチコピーがない", clear: "強みをベースにキャッチコピーを1つ決め、HP・名刺・リーフレットで統一した", isBoss: false, chapter: "04_chapter4.md" },
      { id: 64, name: "フォントとトーン", enemy: "印刷物の雰囲気がバラバラ", clear: "フォント1種類＋言葉遣いのトーンを決め、全ツールで統一した", isBoss: false, chapter: "04_chapter4.md" },
      { id: 65, name: "一貫性の試練", enemy: "バラバラの印象", clear: "HP・名刺・診察券・SNS・看板の全接触ポイントでブランド要素を統一した", isBoss: true, chapter: "04_chapter4.md" }
    ]
  },
  {
    id: 6,
    name: "仕組みの工房",
    subtitle: "経営の仕組み化",
    icon: "⚙️",
    color: "#3498db",
    bgGradient: "linear-gradient(135deg, #3498db 0%, #2980b9 100%)",
    description: "ブランドができた。次は「自分がいなくても回る仕組み」を作る。",
    harryIntro: "ブランドができたね！ でも全部自分でやってたら体が持たないよ。『仕組み』を作って、時間を取り戻そう！",
    harryComplete: "仕組みが全部できた！ 施術以外の時間が大幅に減ったね！ 次はお金の管理だ！",
    reward: "施術以外の時間が大幅に削減された状態",
    title: "時間の支配者",
    levelRange: [41, 50],
    folder: "digital-product-4",
    quests: [
      { id: 66, name: "予約の自動化", enemy: "電話が鳴り止まない", clear: "LINE予約 or Web予約システムを導入し、24時間予約が入る状態にした", isBoss: false, chapter: null },
      { id: 67, name: "HPの自作", enemy: "HP制作に数十万円かかる", clear: "WordPressで自分のHPを立ち上げ、基本ページ（トップ・メニュー・アクセス・予約）を公開した", isBoss: false, chapter: null },
      { id: 68, name: "SEOの種まき", enemy: "検索しても出てこない", clear: "ブログ記事を10本以上書き、地域名＋症状名でのSEO対策を開始した", isBoss: false, chapter: null },
      { id: 69, name: "100記事の壁", enemy: "ブログが続かない", clear: "ブログ記事を100本蓄積した（検索経由の新患集客の土台）", isBoss: false, chapter: null },
      { id: 70, name: "音声の錬金術", enemy: "SNS投稿が負担", clear: "音声録音→文字起こし→4媒体一括投稿の仕組みを作った", isBoss: false, chapter: null },
      { id: 71, name: "LINE公式の城", enemy: "患者さんとの連絡手段がない", clear: "LINE公式アカウントを開設し、予約確認・リマインドを自動化した", isBoss: false, chapter: null },
      { id: 72, name: "カルテのデジタル化", enemy: "紙のカルテが限界", clear: "カルテ・予約管理をデジタル化した（スプレッドシート or アプリ）", isBoss: false, chapter: null },
      { id: 73, name: "Googleビジネスの育成", enemy: "Googleマップで見つからない", clear: "Googleビジネスで週1回以上投稿し、口コミ10件以上を集めた", isBoss: false, chapter: null },
      { id: 74, name: "メルマガの種", enemy: "リピートの仕組みが弱い", clear: "メルマガまたはLINEステップ配信を設計し、10通分のコンテンツを作成した", isBoss: false, chapter: null },
      { id: 75, name: "自動化リスト", enemy: "やることが多すぎる", clear: "1日の業務を全て書き出し、「自動化できるもの」を3つ以上仕組み化した", isBoss: false, chapter: null },
      { id: 76, name: "時間泥棒", enemy: "施術以外に時間を取られすぎる", clear: "施術以外の業務時間を週5時間以下に削減し、週休2日を維持した", isBoss: true, chapter: null }
    ]
  },
  {
    id: 7,
    name: "金庫の迷宮",
    subtitle: "経理・税務",
    icon: "🏦",
    color: "#1abc9c",
    bgGradient: "linear-gradient(135deg, #1abc9c 0%, #16a085 100%)",
    description: "仕組みが回り始めた。でもお金の流れが見えていないと、知らないうちに沈む。",
    harryIntro: "仕組みが動き出したね！ でもお金の流れが見えてないと、気づかないうちに沈んじゃうよ。金庫の迷宮に挑もう！",
    harryComplete: "お金の流れが完全に見えるようになった！ 二刀流の使い手だね！ 最後のワールドへ！",
    reward: "自分のお金の流れを完全に把握した状態",
    title: "二刀流の使い手",
    levelRange: [51, 65],
    folder: "digital-product-6",
    quests: [
      { id: 77, name: "帳簿の灯り", enemy: "確定申告が怖い", clear: "帳簿管理の方法（会計ソフト/スプレッドシート/Claude Code）を決定し、1ヶ月つけた", isBoss: false, chapter: "01_chapter1.md" },
      { id: 78, name: "仕訳の型", enemy: "何をどう記帳すればいいかわからない", clear: "治療院の頻出仕訳パターン5つを習得した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 79, name: "65万の鍵", enemy: "青色申告の条件がわからない", clear: "複式簿記＋BS/PL作成＋e-Tax電子申告の3条件を理解し、体制を整えた", isBoss: false, chapter: "01_chapter1.md" },
      { id: 80, name: "PLの目", enemy: "売上しか見ていない", clear: "今月のPL（売上・経費・利益・経費率）を自分の数字で作成した", isBoss: false, chapter: "02_chapter2.md" },
      { id: 81, name: "BSの目", enemy: "資産と負債の全体像が見えない", clear: "BS（資産・負債・純資産）を自分の数字で作成した", isBoss: false, chapter: "02_chapter2.md" },
      { id: 82, name: "キャッシュの目", enemy: "来月お金が回るかわからない", clear: "来月の入金予定・出金予定を書き出し、月末残高を予測した", isBoss: false, chapter: "02_chapter2.md" },
      { id: 83, name: "月次の儀式", enemy: "経理を後回しにしてしまう", clear: "毎月30分の月次レポート作成を3ヶ月継続した", isBoss: false, chapter: "02_chapter2.md" },
      { id: 84, name: "e-Taxの道", enemy: "マイナンバーカードがない", clear: "マイナンバーカード取得＋e-Tax利用者識別番号取得を完了した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 85, name: "確定申告の冒険", enemy: "申告書の作り方がわからない", clear: "青色申告決算書＋確定申告書を自力で作成し、e-Taxで電子申告した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 86, name: "保管の結界", enemy: "領収書をどこまで保管するかわからない", clear: "帳簿7年・領収書7年の保管体制を整えた", isBoss: false, chapter: "01_chapter1.md" },
      { id: 87, name: "二刀流の扉", enemy: "保険料が高すぎる", clear: "マイクロ法人のシミュレーション（社会保険料削減額 vs 法人維持コスト）を行った", isBoss: false, chapter: "03_chapter3.md" },
      { id: 88, name: "法人の設計図", enemy: "法人設立の手順がわからない", clear: "合同会社設立の基本事項（商号・事業目的・資本金・決算月）を決めた", isBoss: false, chapter: "04_chapter4.md" },
      { id: 89, name: "法人設立の大魔王", enemy: "法人なんて自分には無理", clear: "合同会社を設立し、社会保険加入＋国保脱退を完了した（or メリットなしと判断した）", isBoss: true, chapter: "04_chapter4.md" }
    ]
  },
  {
    id: 8,
    name: "自由の城",
    subtitle: "固定費最適化",
    icon: "🏰",
    color: "#e91e63",
    bgGradient: "linear-gradient(135deg, #e91e63 0%, #c2185b 100%)",
    description: "お金が見えるようになった。最後は「出ていくお金」を最小化して、真の自由を手に入れる。",
    harryIntro: "最後のワールドだよ！ ここまで来たら、もうゴールは近い。『出ていくお金』を減らして、本当の自由を手に入れよう。固定費を倒したら、君は誰にも縛られない治療家だ！",
    harryComplete: "全ワールドクリア、おめでとう！ 君はもう立派な『自立した治療家』だよ。ここからが本当の冒険の始まりだ！",
    reward: "身軽で自由な経営スタイル",
    title: "自由の民",
    levelRange: [66, 80],
    folder: "digital-product-8",
    quests: [
      { id: 90, name: "固定費の亡霊", enemy: "何もしてないのにお金が出ていく", clear: "全固定費を書き出し、「必要」「見直し可能」「不要」に分類した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 91, name: "スマホの解放", enemy: "スマホ代が高い", clear: "格安SIMに変更し、月3,000〜5,000円を削減した（or 既に最適化済みと確認）", isBoss: false, chapter: "01_chapter1.md" },
      { id: 92, name: "エネルギーの最適化", enemy: "電気・ガスが高い", clear: "電力会社の見直し＋ガス会社の見直し（相見積もり）を実施した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 93, name: "保険の棚卸し", enemy: "保険に入りすぎている", clear: "全保険を見直し、「なぜ入っているか」説明できないものを解約した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 94, name: "賢者の買い物", enemy: "定価で買っている", clear: "ポイントサイト・楽天マラソンなどを活用して1つ以上買い物した", isBoss: false, chapter: "02_chapter2.md" },
      { id: 95, name: "錬金術師", enemy: "生活費が経費にならない", clear: "生活費を1つ「コンテンツ素材化」して事業経費にした", isBoss: false, chapter: "03_chapter3.md" },
      { id: 96, name: "見える化の鏡", enemy: "毎月いくら使っているかわからない", clear: "スプレッドシートで月次の生活費管理を開始し、2ヶ月継続した", isBoss: false, chapter: "04_chapter4.md" },
      { id: 97, name: "退職金の種", enemy: "老後の備えがない", clear: "小規模企業共済 or iDeCo or NISAの少なくとも1つを開始した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 98, name: "守りの収入", enemy: "自院の売上だけでは不安", clear: "お勤め先（デイサービス・訪問マッサージなど）を確保し、週1回以上通い始めた", isBoss: false, chapter: "01_chapter1.md" },
      { id: 99, name: "お勤めの最適化", enemy: "お勤めの時間と収入のバランスが悪い", clear: "週1〜3回の半日勤務に調整し、月額収入と自院への影響を最適化した", isBoss: false, chapter: "01_chapter1.md" },
      { id: 100, name: "自由の門番", enemy: "まだ不安が残る", clear: "守りの収入＋固定費削減＋自院売上の3本柱で、月次収支を安定させた", isBoss: true, chapter: "04_chapter4.md" }
    ]
  }
];

// レベルと称号の定義
const LEVELS = [
  { level: 1, title: "見習い治療家", requiredQuests: 0 },
  { level: 5, title: "装備完了の冒険者", requiredQuests: 13 },
  { level: 13, title: "心が整った治療家", requiredQuests: 26 },
  { level: 20, title: "街の顔", requiredQuests: 40 },
  { level: 30, title: "技の継承者", requiredQuests: 53 },
  { level: 40, title: "旗を立てた者", requiredQuests: 65 },
  { level: 50, title: "時間の支配者", requiredQuests: 76 },
  { level: 65, title: "二刀流の使い手", requiredQuests: 89 },
  { level: 80, title: "自由の民", requiredQuests: 100 },
  { level: 100, title: "自立した治療家", requiredQuests: 100 }
];

// 特殊称号
const SPECIAL_TITLES = [
  { id: "challenger30", name: "30日チャレンジャー", questId: 25, description: "30日間毎日提案した" },
  { id: "writer100", name: "100記事の書き手", questId: 69, description: "ブログ100本達成" },
  { id: "publisher", name: "出版者", questId: 58, description: "Kindle出版した" },
  { id: "guardian", name: "守りの戦士", questId: 98, description: "お勤め収入を確保した" },
  { id: "alchemist", name: "錬金術師", questId: 95, description: "生活費を事業経費化した" }
];
